### ISSUE TITLE
Investigate USAT Viewers 

### ISSUE THREAD

**Issue by migreva** [michigan-com/chartbeat-api#2]
The array used to draw the Viewers graph for on.thepul.se disappears from time to time as a result of being passed an empty array. Will need to investigate why it's failing in the chartbeat-api calls

In addition, we should also look into dashbeat and change the logic around on the viewers dashboard to not re-draw the viewers dashboard if we get an empty array in the middle of the day. Should look into the `componentShouldUpdate` method

**Comment by andreyvit** [comment]
Closing the old issues.
